function main() {
  return "running app";
}

main().then(res => console.log(res).catch(err => console.log(err))
